### ISSUE TITLE
`inheritAttrs` is not working

### ISSUE THREAD

**Issue by sxzz** [vuejs/vue-vapor#253]
`inheritAttrs` may affect performance:

`<div :id="expr" :title="expr2" />` 

- It has two separate dynamic props. If an expression changes, just update the corresponding prop.
- By default, `inheritAttrs` is enabled. Since a prop might be overridden, neither of these can be optimized.
- Every time either `expr`, `expr2`, or `$attrs` change, the entire props need to be re-patched.

**Comment by LittleSound** [comment]
Certain designs in Vapor that are incompatible with Vue Core might achieve better performance. This also applies to situations like implementing built-in directives.

Perhaps when we need to implement Vue4, we can consider such things :P
