### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by dannysmc95** [vuejs/vue-vapor#285]
Hey, just wondering what the status is, I can see the demo noted in the readme doesn't work anymore, i.e. the v-model doesn't actually work, wondering if this is just a bug with the demo, rather than the project?

**Comment by sxzz** [comment]
The `v-model` custom directive is temporarily dropped and will be resolved soon. See https://github.com/vuejs/vue-vapor/pull/278

**Comment by sxzz** [comment]
Fixed via #278
